name: shipperit
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: any 
  google_fonts: ^2.1.1
  carousel_slider: ^4.0.0  
  font_awesome_flutter: ^9.2.0
  flutter_staggered_grid_view: ^0.6.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/onBoarding/
    - assets/images/homePage/
  
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Bold-Font.ttf
          weight: 700
        - asset: fonts/Helvetica-Light.ttf
          weight: 100